CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  telepon VARCHAR(20) NOT NULL,
  role ENUM('ADMIN', 'PUSTAKAWAN', 'PENGUNJUNG') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  thumbnail VARCHAR(255),
  author VARCHAR(50) NOT NULL,
  publisher VARCHAR(50) NOT NULL,
  published_at DATE,
  status ENUM('AVAILABLE', 'NOT AVAILABLE') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE checkouts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  pustakawan_id INT NOT NULL,
  taken_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (pustakawan_id) REFERENCES users(id)
);

CREATE TABLE checkout_details (
  id INT PRIMARY KEY AUTO_INCREMENT,
  checkout_id INT NOT NULL,
  book_id INT NOT NULL,
  return_date DATE,
  accepted ENUM('ACCEPTED', 'NOT ACCEPTED') DEFAULT 'NOT ACCEPTED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (checkout_id) REFERENCES checkouts(id),
  FOREIGN KEY (book_id) REFERENCES books(id)
);

